### ISSUE TITLE
Post error

### ISSUE THREAD

**Issue by bitog** [nopp/alertmanager-webhook-telegram#1]
Hi there,

I am currently getting the following error: "POST /alert HTTP/1.1" 200 -

Any idea how I can solve that issue?

Thanks in advance.

**Comment by nopp** [comment]
Hi, this isn't an error, 200 is returned OK  from the POST :)

**Comment by bitog** [comment]
Ah ok, understand. I was using the github webhooks. Maybe thats the issue.

**Comment by nopp** [comment]
You need only configure chatID and botID, I'm using in production and working fine!

**Comment by bitog** [comment]
Yes, I setup the chatID and botID. Once a post or commit is being made the bot picks it up however only "Failed to send via Flask to Telegram!" is being posted. 
Do I have to add the "app.secret_key" to "Secret" in Github? I actually also tried that but didnt help. I am also using "application/json" as content type. 
In the response / body section it just says {}, is that maybe an issue? See screenshot: [https://imgur.com/oSFYpF3.png](https://imgur.com/oSFYpF3.png)

**Comment by nopp** [comment]
Github? this script works only alertmanager+prometheus.
