### ISSUE TITLE
better logging

### ISSUE THREAD

**Issue by mator** [nopp/alertmanager-webhook-telegram#12]
Sometimes i receive just a 'Error' message in telegram. 

Is it possible to enhance logging within flask to log JSON/message which produced error ?! 

Something like: 

```
    except:
        bot.sendMessage(chat_id=chatID, text="Error!")
        app.logger.info("Exception:")
        app.logger.info("\t%s : %s", timedate, content) # use timedate if content does not have time
        return "Alert nOK", 200

```

would it work? (writting `content` or even raw `request.get_data()` to `flaskAlert.log` ) ? I probably would prefer to log to `sys.stderr` , since running in a docker container.

Since `Output.txt` is only holds last alert message. 

Thanks.

**Comment by nopp** [comment]
I'll work on this :)

**Comment by nopp** [comment]
@mator better log now ;)

`
INFO:werkzeug: * Running on http://0.0.0.0:9119/ (Press CTRL+C to quit)

INFO:flaskAlert:	Expecting ',' delimiter: line 1 column 98 (char 97)

INFO:werkzeug:127.0.0.1 - - [18/Apr/2020 03:21:54] "POST /alert HTTP/1.1" 200 -
`

At telegram we receive:
Error to read json: Expecting ',' delimiter: line 1 column 98 (char 97)
