### ISSUE TITLE
Compromised secret key

### ISSUE THREAD

**Issue by carc1n0gen** [nopp/alertmanager-webhook-telegram#13]
You have your secret key right in the code https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L9

Therefore it is compromised, and an attacker can sign there own malicious cookies and the app will accept them.

**Comment by nopp** [comment]
Uhum, but I dont use this key ;).
