### ISSUE TITLE
Latest update break bot functionality if username or password is not set

### ISSUE THREAD

**Issue by Geekete** [nopp/alertmanager-webhook-telegram#5]
Please implement tags for your docker images other than "latest". Your latest commit broke bot functionality by forcing usage of username and password which is not required nor needed in our case.

Now alertmanager returns this error and cannot send messages:
level=error ts=2019-08-09T10:26:36.082322163Z caller=dispatch.go:280 component=dispatcher msg="Notify for alerts failed" num_alerts=2 err="cancelling notify retry for \"webhook\" due to unrecoverable error: unexpected status code 401 from http://alertmanager-bot-supply/alert"
Nothing else has been changed from our side apart from automatically pulling your latest docker image.

Could you please create a tag that would point to specific commit so we can still use your implementation of telegram bot without username or password?

**Comment by nopp** [comment]
You need only pass 2 environments variable in your deployment (if you are using k8s), or if you use only in docker, just run again with  -e "username=" -e "password=", its simple to "fix".

**Comment by Geekete** [comment]
Even passing empty environment variables still returns the same error. Only fix I was able to apply was setting app.config['BASIC_AUTH_FORCE'] = False. At least allow people to specify this value through environment variables.

Otherwise I don't see any other solution as to fork from your repository as many have done already.

**Comment by nopp** [comment]
@Geekete

**My tests:**

`➔ ~ $ docker run -d --name telegram-bot -e "bottoken=509742575:XXXXXXFWp9JToRobViKoDvkXXXXX" -e "chatid=XXXX86XX" -e "username=user" -e "password=123" -p 9119:9119 nopp/alertmanager-webhook-telegram:latest
Unable to find image 'nopp/alertmanager-webhook-telegram:latest' locally
latest: Pulling from nopp/alertmanager-webhook-telegram
5d20c808ce19: Already exists 
f9edd728dac0: Pull complete 
28b39252ca83: Pull complete 
294a5374415f: Pull complete 
Digest: sha256:37fe901e3bc673779d87e7e2a35fa8278f364528be6099d87569f9fa3e63ea63
Status: Downloaded newer image for nopp/alertmanager-webhook-telegram:latest
af8c287d59f966526a62075c856ebaf489b1831e165c3e2021ca03e6b2332e55
`

`
➔ ~ $ docker container ls
CONTAINER ID        IMAGE                                       COMMAND             CREATED             STATUS              PORTS                    NAMES
af8c287d59f9        nopp/alertmanager-webhook-telegram:latest   "./run.sh"          6 seconds ago       Up 2 seconds        0.0.0.0:9119->9119/tcp   telegram-bot
`

**Running local on my server ..... and running curl:**

`➔ ~ $ curl -XPOST --data '{"status":"resolved","groupLabels":{"alertname":"instance_down"},"commonAnnotations":{"description":"i-0d7188fkl90bac100 of job ec2-sp-node_exporter has been down for more than 2 minutes.","summary":"Instance i-0d7188fkl90bac100 down"},"alerts":[{"status":"resolved","labels":{"name":"olokinho01-prod","instance":"i-0d7188fkl90bac100","job":"ec2-sp-node_exporter","alertname":"instance_down","os":"linux","severity":"page"},"endsAt":"2019-07-01T16:16:19.376244942-03:00","generatorURL":"http://pmts.io:9090","startsAt":"2019-07-01T16:02:19.376245319-03:00","annotations":{"description":"i-0d7188fkl90bac100 of job ec2-sp-node_exporter has been down for more than 2 minutes.","summary":"Instance i-0d7188fkl90bac100 down"}}],"version":"4","receiver":"infra-alert","externalURL":"http://alm.io:9093","commonLabels":{"name":"olokinho01-prod","instance":"i-0d7188fkl90bac100","job":"ec2-sp-node_exporter","alertname":"instance_down","os":"linux","severity":"page"}}' http://user:123@localhost:9119/alert
Alert OK`


**Worked normaly, and telegram image, below.**

https://ibb.co/sKC1vDb

**Comment by Geekete** [comment]
Alright, providing fake user and password and updating alertmanager configuration to use URL as http://fakeuser:fakepass@.... etc. works. Thank you for explaining this with an example.

However, please consider my initial request to implement versioning for your docker image. It's not hard to do and would allow people to specify which version of your code to use.

**Comment by nopp** [comment]
> Alright, providing fake user and password and updating alertmanager configuration to use URL as http://fakeuser:fakepass@.... etc. works. Thank you for explaining this with an example.
> 
> However, please consider my initial request to implement versioning for your docker image. It's not hard to do and would allow people to specify which version of your code to use.

Yes, I'll do this :)
