### ISSUE TITLE
docker: Error response from daemon: manifest for nopp/alertmanager-webhook-telegram:latest not found.

### ISSUE THREAD

**Issue by atorrente75** [nopp/alertmanager-webhook-telegram#7]
docker run -d --name telegram-bot -e "bottoken=mytoken" -e "chatid=mychat" -e "username=" -e "password=" -p 9119:9119 nopp/alertmanager-webhook-telegram:latest

->
Unable to find image 'nopp/alertmanager-webhook-telegram:latest' locally
docker: Error response from daemon: manifest for nopp/alertmanager-webhook-telegram:latest not found.

docker pull nopp/alertmanager-webhook-telegram:latest                                                                                            

->
Error response from daemon: manifest for nopp/alertmanager-webhook-telegram:latest not found

**Comment by nopp** [comment]
This is not an error, you can see the versions available at docker hub.
