### ISSUE TITLE
chat id fix

### ISSUE THREAD

**Issue by mator** [nopp/alertmanager-webhook-telegram#9]
Issues for a new PR (coming soon [tm]) :

- remove minus from chatid in code, chat should be passed as is, since there's user chat with positive number and group chats with negative (minus prefix) number
- be more verbose (in logs) on startup (admin user / chatid)
- fail to run if bottoken or chatid is not set with log message (better than getting a call/stack trace)
- better logging in docker (failed to send message or message sent successfully) , instead of plain "error".

update 23.12.2019 : commit for first 3 items are ready,  just need to make a descriptive PR

**Comment by nopp** [comment]
PR accepted.
